name: Modeling Pipeline

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  modeling_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository }}/modeling:latest

    - name: Run Modeling pipeline
      env:
        ACC_NAME: ${{ secrets.ACC_NAME }}
        ACC_KEY: ${{ secrets.ACC_KEY }}
        CONTEINER: ${{ secrets.CONTEINER }}
        FOLDER: ${{ secrets.FOLDER }}
        MODEL_START_DATE: ${{ secrets.MODEL_START_DATE }}
        MODEL_SPLIT_DATE: ${{ secrets.MODEL_SPLIT_DATE }}
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/models:/app/models \
          -e ACC_NAME -e ACC_KEY -e CONTEINER -e FOLDER \
          -e MODEL_START_DATE -e MODEL_SPLIT_DATE \
          ghcr.io/${{ github.repository }}/modeling:latest \
          python -m src.models.modeling_pipeline

    - name: Upload trained model
      uses: actions/upload-artifact@v2
      with:
        name: trained-model
        path: models/trained_model.joblib