name: Data Pipeline

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 03:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL pipeline
      env:
        ACC_NAME: ${{ secrets.ACC_NAME }}
        ACC_KEY: ${{ secrets.ACC_KEY }}
        CONTEINER: ${{ secrets.CONTEINER }}
        FOLDER: ${{ secrets.FOLDER }}
        START_DATE: ${{ secrets.START_DATE }}
        END_DATE: ${{ secrets.END_DATE }}
        AREA_CODE: ${{ secrets.AREA_CODE }}
      run: python -m src.data.pipeline

  scoring_job:
    needs: etl_job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.12'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Scoring pipeline
      env:
        ACC_NAME: ${{ secrets.ACC_NAME }}
        ACC_KEY: ${{ secrets.ACC_KEY }}
        CONTEINER: ${{ secrets.CONTEINER }}
        FOLDER: ${{ secrets.FOLDER }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python -m src.models.scoring_pipeline