name: ETL Pipeline

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 03:00 UTC, which is midnight in São Paulo time (UTC-3)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL pipeline
      env:

        ACC_NAME: ${{ secrets.ACC_NAME }}
        ACC_KEY: ${{ secrets.ACC_KEY }}
        CONTEINER: ${{ secrets.CONTEINER }}
        FOLDER: ${{ secrets.FOLDER }}
        AZURE_FILE_NAME: ${{ secrets.AZURE_FILE_NAME }}
        START_DATE: ${{ secrets.START_DATE }}

      run: python data_pipeline.py

  modeling_job:
    needs: etl_job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run ETL pipeline
      env:

        MODEL_START_DATE: ${{ secrets.MODEL_START_DATE }}
        MODEL_SPLIT_DATE: ${{ secrets.MODEL_START_DATE }}
        LEVELS: ${{ secrets.MODEL_START_DATE }}

      run: python modeling_pipeline.py
