name: ETL Pipeline

on:
  schedule:
    - cron: '0 3 * * *' # Runs daily at 03:00 UTC (before the business day starts)
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  etl_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pendulum pandas boto3

    - name: Run ETL pipeline
      env:
        START_DATE: '2022-01-01'
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        S3_PREFIX: 'ons-data'
        AREA_CODE: 'SP'
      run: python etl_pipeline.py
